### ISSUE TITLE
Application Crashes in C# UWP Application

### ISSUE THREAD

**Issue by nickrandolph** [Microsoft/winsdkfb#65] opened 2015-10-06 05:03 UTC
After login, the application crashes on the current insider preview of Windows 10 Mobile with some reference to an internal Edge exception.

**Comment by adiviness** [comment] 2015-10-06 19:45
Can you provide some more information? What is the exact text of the exception? Is this with C# or C++?

**Comment by nickrandolph** [comment] 2015-10-08 22:44
Here's a sample app that shows the following three issues (https://dl.dropboxusercontent.com/u/10291137/FacebookConnectSample.zip)
> When run on Windows 10 Mobile (emulator or real device), application crashes after login
> On desktop, if you Login, then Logout, if you attempt to Log in again you don't see the login prompt (ie you can't change user)
> On desktop, if you Login, close the app; when you restart the application the sdk indicates that FB is still authenticated but if you attempt to post using the dialog, you just see a blank overlay. If you call Login first, the dialog is correctly populated.

Feel free to reach out to me if you aren't able to repro these issues. These are all high priority issues that need a resolution before we could consider using the SDK

**Comment by adiviness** [comment] 2015-10-09 00:20
On desktop, I wasn't able to reproduce your problem. When the app is restarted, how is it indicating that it is still authenticated to you? If I log in, restart the app, and then try the "Post Dialog" button, the `Sess` variable hasn't been set up yet so the `PostMessageToFacebookShowDialogue` function would fail. By pressing the Login button, you are setting the `Sess` variable and so the `PostMessageToFacebookShowDialogue` function would no longer create an exception in its try/catch block.

As far as logging out and changing the user, check out #31.

For mobile, something is crashing, however it does seem to be successfully performing a login, as I can restart the app and continue to use it normally. It doesn't seem to be a problem with the sdk itself, we'll investigate if a workaround is possible for the short term.

**Comment by nickrandolph** [comment] 2015-10-09 00:23
The question for desktop is how do we re-establish the session without prompting the user to login again – we don’t want them to see the login dialog again if they’re already signed in?

Nick Randolph | Built to Roam Pty Ltd | Microsoft MVP – Windows Phone Development | +61 412 413 425 | @btroam | skype:nick_randolph
The information contained in this email is confidential. If you are not the intended recipient, you may not disclose or use the information in this email in any way. Built to Roam Pty Ltd does not guarantee the integrity of any emails or attached files. The views or opinions expressed are the author's own and may not reflect the views or opinions of Built to Roam Pty Ltd.

**Comment by adiviness** [comment] 2015-10-09 00:41
I believe that you will have to call `LoginAsync` each time, however if the user had previously logged in and that access token is still valid then the view prompting the user to log in won't show. The sdk caches the token and will use that if it is still valid.

**Comment by nickrandolph** [comment] 2015-10-09 00:53
I’m ok with having to call Login each time the app launches. However, you’re statement that the log in won’t show is not correct, the dialog attempts to show (ie you can see the dialog border appear – see image) which is not a great user experience.

[cid:image002.jpg@01D10289.0AD150C0]

Nick Randolph | Built to Roam Pty Ltd | Microsoft MVP – Windows Phone Development | +61 412 413 425 | @btroam | skype:nick_randolph
The information contained in this email is confidential. If you are not the intended recipient, you may not disclose or use the information in this email in any way. Built to Roam Pty Ltd does not guarantee the integrity of any emails or attached files. The views or opinions expressed are the author's own and may not reflect the views or opinions of Built to Roam Pty Ltd.

**Comment by adiviness** [comment] 2015-10-09 17:07
I agree, preventing the web view login dialog from appearing at all when it isn't necessary is something that we'd like to fix.

**Comment by adiviness** [comment] 2015-11-05 22:41
For the crash you were experiencing on mobile, it turned out to be a problem not with the sdk but with the webview. It has since been fixed and will be released in a later windows flight.

**Closed by adiviness** 2015-11-05 22:41 UTC
